Feature
Marra2342/Hello-word pull request #1
Opened 2022-05-25 12:51 UTC by Marra2342

Added basic files needed for the exercise. Index.html, style.css, a valid README.md and other files alongside the linters.

2022-05-25 13:43 UTC, Kakalanp requested changes
# Hello there @Marra2342! <img src="https://user-images.githubusercontent.com/1303154/88677602-1635ba80-d120-11ea-84d8-d263ba5fc3c0.gif" width="28px" alt="hi">

### Good job so far! :tada: 

There are some issues that you still need to work on to go to the next project but you are almost there! :pinching_hand: 

<img src="https://media.giphy.com/media/Qaxd5XpgDWMso/giphy.gif" alt="so close">

## Highlights :+1: 
- No linter errors :heavy_check_mark:
- Solid pull request :scroll:
- Espectacular first try! :monocle_face: 

## Required Changes ♻️

Great job using the README template! But don't forget to tweak it for each project, adding the correct info to it, this will make your repo more professional :briefcase: 
![image](https://user-images.githubusercontent.com/78335447/170276427-f24764bf-0647-43de-a185-4da892c40961.png)


## Optional suggestions

It seems that you have accidentally added [an empty file](https://github.com/Marra2342/Hello-word/blob/30c3a10024f968f6e0117dd56ac6515956c5a317/Hello-World) in your repo, kindly consider deleting it :wink:  

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-25 13:43 UTC, Kakalanp commented on style.css
> +  color: forestgreen;
[OPTIONAL]

Sometimes using names for colors is considered bad practice, you could change it to something like: `color: #228b22;`

2022-05-25 15:05 UTC, Marra2342 commented on style.css
> +  color: forestgreen;
Thank you, will change it.

2022-05-26 16:40 UTC, Ismailco approved these changes
### Hi @Marra2342,
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)


## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 16:40 UTC, Ismailco commented on README.md
>  ### Prerequisites
- [ ] [Optional] You can remove this section if it's empty and not used, or add some information inside it

2022-05-26 16:40 UTC, Ismailco commented on README.md
>  ![](https://img.shields.io/badge/Microverse-blueviolet)
- [ ] [OPTIONAL] The Pull Request should have a descriptive title telling you what changes are inside, now the title ```Feature``` is not descriptive, please change it to something meaningful

2022-05-26 17:35 UTC, merged